title: poetry-generator-scratch2
hero_image: images/banner.png
description: poetry-generator-scratch2 description
version: 4
listed: false
copyedit: false
last_tested: "2019-02-25"
steps:
  - title: Introduction
  - title: Step title
  - title: What next?
